### PR TITLE
Docs: add floodwaiter example

### PR DESCRIPTION
**Pull request by TeaDove**
Floodwaiter example added with new RunMiddleware option.  

(not sure if RunMiddleware function is written correctly, but in my project it works as expected)

### CODE REVIEW

**Comment by TeaDove** [comment]
@celestix I think flood waiter example is very important, cause flood-waiter almost always is mandatory. 
If you want, I can add waiter to new seperate example

**Comment by celestix** [comment]
> @celestix I think flood waiter example is very important, cause flood-waiter almost always is mandatory. 
> If you want, I can add waiter to new seperate example

Hello, I think you're right. It would be better to keep it as a separate example.

**Comment by TeaDove** [comment]
@celestix done it!

**Comment by celestix** [comment]
Thank you for this valuable addition to the examples!

**Pull request merged**
